In [89]:
#import Libraries
import urllib
import csv
from bs4 import BeautifulSoup
from urllib.request import urlopen
from urllib.request import Request, urlopen

data = []
#declare url
# urltoScrap = "https://www.cheki.com.ng/vehicles"

for i in range(33,601):

    urltoScrap = "https://www.cheki.com.ng/vehicles?page="+str(i)


    req = Request(urltoScrap, headers={'User-Agent': 'Mozilla/5.0'})

    #query the url
    page = urlopen(req).read()
    # page = urlopen(urltoScrap)

    #parse the html
    parsed_html = BeautifulSoup(page, 'html.parser')

    cars = parsed_html.find_all('li', class_ = 'listing-unit')


    for i in range(len(cars)):
        first = cars[i]

        name = first.find('div', class_ = 'listing-unit__title').text.strip()
        if (name.startswith('New')):
            name = name[4:] #Removes the \n character.

        location = first.find('div', class_ = 'listing-unit__location').text.strip()
        other_details = first.find_all('div', class_ = 'listing-unit__detail')
        price = first.find('div', class_ = 'listing-unit__price').text.strip()
        price = price[1:] #Removes the naira sign
#         Convert Price to int and remove commas
        split_price = price.split(',')
        price = ''.join(split_price)
        price = int(price)


    # print(len(other_details))

    #     If Mileage value is not available:
        if (len(other_details) >= 5):
            usedtype = other_details[0].get_text()
            year = other_details[1].get_text()
            mileage = other_details[3].get_text()
            transmission = other_details[4].get_text()
        elif(len(other_details) == 4):
            usedtype = other_details[0].get_text()
            year = other_details[1].get_text()
            mileage = ''
            transmission = other_details[3].get_text()
            
        data.append([name,location,usedtype,year,mileage,transmission,price])


# print(data)
    
myFile = open('cars_data.csv', 'w', newline='')
with myFile:
    writer = csv.writer(myFile)
    writer.writerows(data)   

print("Scrapped!!!\n")
print('Amount of data: '+str(len(data)))

Scrapped!!!

Amount of data: 11360


In [90]:
11360/20

568.0

In [91]:
568+32

600

In [92]:
myFile = open('cars_data.csv', 'a', newline='')
with myFile:
    writer = csv.writer(myFile)
    writer.writerows(data)   

IndentationError: expected an indented block (<ipython-input-92-9631c8ed993a>, line 4)

In [93]:
myFile = open('cars_data.csv', 'w', newline='')
with myFile:
    writer = csv.writer(myFile)
    writer.writerows(data)   

In [94]:
print('hi')

hi


In [95]:
print(len(data))

11360


In [96]:
import numpy as np

In [97]:
np_data = np.array(data)

In [98]:
np_data[1]

array(['Toyota Camry XLE V6', 'Lagos', 'Foreign Used', '2013', '',
       'Automatic', '6700000'],
      dtype='<U67')

In [100]:
np_data[0][2]

'Foreign Used'

In [108]:
new_data = []
for i in range(1,len(np_data)):
    if(np_data[i][4] != ''):
        new_data.append(np_data[i])

print(new_data)
print('len= '+str(len(new_data)))

[array(['Volkswagen LT', 'Lagos', 'Foreign Used', '1998', '280000km',
       'Manual', '2000000'],
      dtype='<U67'), array(['Acura MDX Sport Package', 'Rivers', 'Locally Used', '2007',
       '143000km', 'Automatic', '3500000'],
      dtype='<U67'), array(['Lexus ES 350', 'Delta', 'Foreign Used', '2007', '119000km',
       'Automatic', '4400000'],
      dtype='<U67'), array(['Mercedes-Benz GLK 350 4MATIC', 'Lagos', 'Foreign Used', '2014',
       '400000km', 'Automatic', '15000000'],
      dtype='<U67'), array(['Honda Pilot EX Automatic', 'Lagos', 'Foreign Used', '2004',
       '98523km', 'Automatic', '1850000'],
      dtype='<U67'), array(['Toyota Camry 2.4', 'Lagos', 'Foreign Used', '2003', '120523km',
       'Automatic', '1620000'],
      dtype='<U67'), array(['Toyota Corolla 1.8 VVTL-i', 'Lagos', 'Foreign Used', '2003',
       '78024km', 'Automatic', '1880000'],
      dtype='<U67'), array(['Lexus RX 300', 'Lagos', 'Locally Used', '2000', '130234km',
       'Automatic', '1450000']

In [109]:
myFile = open('new_cars_data.csv', 'w', newline='')
with myFile:
    writer = csv.writer(myFile)
    writer.writerows(new_data) 

In [110]:
unique,pos = np.unique(new_data,return_inverse=True) #Finds all unique elements and their positions
counts = np.bincount(pos)                     #Count the number of each unique element
maxpos = counts.argmax()                      #Finds the positions of the maximum count

print(unique[maxpos],counts[maxpos])

Automatic 2790


In [117]:
new_data[:,0]

TypeError: list indices must be integers or slices, not tuple

In [122]:
str_sam = "10000km"

In [123]:
int(str_sam[:-2])

10000

In [127]:
new_data

[array(['Volkswagen LT', 'Lagos', 'Foreign Used', '1998', '280000km',
        'Manual', '2000000'],
       dtype='<U67'),
 array(['Acura MDX Sport Package', 'Rivers', 'Locally Used', '2007',
        '143000km', 'Automatic', '3500000'],
       dtype='<U67'),
 array(['Lexus ES 350', 'Delta', 'Foreign Used', '2007', '119000km',
        'Automatic', '4400000'],
       dtype='<U67'),
 array(['Mercedes-Benz GLK 350 4MATIC', 'Lagos', 'Foreign Used', '2014',
        '400000km', 'Automatic', '15000000'],
       dtype='<U67'),
 array(['Honda Pilot EX Automatic', 'Lagos', 'Foreign Used', '2004',
        '98523km', 'Automatic', '1850000'],
       dtype='<U67'),
 array(['Toyota Camry 2.4', 'Lagos', 'Foreign Used', '2003', '120523km',
        'Automatic', '1620000'],
       dtype='<U67'),
 array(['Toyota Corolla 1.8 VVTL-i', 'Lagos', 'Foreign Used', '2003',
        '78024km', 'Automatic', '1880000'],
       dtype='<U67'),
 array(['Lexus RX 300', 'Lagos', 'Locally Used', '2000', '130234km',
        '

In [126]:
np_new_data

array([['Volkswagen LT', 'Lagos', 'Foreign Used', ..., '280000km',
        'Manual', '2000000'],
       ['Acura MDX Sport Package', 'Rivers', 'Locally Used', ...,
        '143000km', 'Automatic', '3500000'],
       ['Lexus ES 350', 'Delta', 'Foreign Used', ..., '119000km',
        'Automatic', '4400000'],
       ..., 
       ['Honda Accord', 'Lagos', 'Foreign Used', ..., '75345km',
        'Automatic', '2900000'],
       ['Mercedes-Benz ML350', 'Lagos', 'Foreign Used', ..., '63563km',
        'Automatic', '4650000'],
       ['Mercedes-Benz ML350', 'Lagos', 'Foreign Used', ..., '62331km',
        'Automatic', '5400000']],
      dtype='<U67')

In [130]:
for i in range(len(new_data)):
    new_data[i][4] = new_data[i][4][:-2]

In [140]:
for i in range(len(new_data)):
    new_data[i][4] = int(new_data[i][4])

In [143]:
myFile = open('new_cars_data.csv', 'w', newline='')
with myFile:
    writer = csv.writer(myFile)
    writer.writerows(new_data)   

In [144]:
np.array([1,2,4])


array([1, 2, 4])

In [145]:
# >>> le = preprocessing.LabelEncoder()
# >>> le.fit(["paris", "paris", "tokyo", "amsterdam"])
# LabelEncoder()
# >>> list(le.classes_)
# ['amsterdam', 'paris', 'tokyo']
# >>> le.transform(["tokyo", "tokyo", "paris"]) 
# array([2, 2, 1]...)
# >>> list(le.inverse_transform([2, 2, 1]))
# ['tokyo', 'tokyo', 'paris']


In [171]:
price = []
for i in range(len(new_data)):
    price.append(int(new_data[i][6]))

In [173]:
# name_of_cars
# location
# condition
# year - int
# mileage - int
# transmission
# price - int

In [235]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()

le.fit(name_of_cars)

LabelEncoder()

In [246]:
# tran_name
# tran_location
# tran_condition
# tran_transmission
le.inverse_transform(626)

'Volkswagen LT'

In [261]:
import numpy as np
from sklearn import linear_model

_name,_location,_condition,_year,_mileage,_trans,Y = np.genfromtxt('car_data_final.csv', delimiter=',', dtype=int, unpack=True)

# Combining the X values
# TODO Convert intent and expression to ordinal data
X =  np.column_stack((_name,_location,_condition,_year,_mileage,_trans))

# Training the Model
reg = linear_model.LinearRegression()
reg.fit (X, Y)
reg.coef_

array([ -2.16558395e+03,   3.54670127e+05,  -3.14991822e+06,
         1.11556027e+06,  -7.52747811e-01,   4.71648640e+06])

In [263]:
reg.predict([[4,18,2,2007,143000,0]])

array([ 4192453.512043])